#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    Feb 26, 2022 12:15:32 PM +07  platform: Windows NT
#    Feb 26, 2022 12:29:43 PM +07  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import GUIcandidatemodify

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = GUIcandidatemodify.Toplevel1(_top1)
    root.mainloop()

def calculateExtracharge(*args):
    print('GUIcandidatemodify_support.calculateExtracharge')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

def deleteTransaction(*args):
    print('GUIcandidatemodify_support.deleteTransaction')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

def exitProgram(*args):
    print('GUIcandidatemodify_support.exitProgram')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

def export(*args):
    print('GUIcandidatemodify_support.export')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

def makBuffalotransaction(*args):
    print('GUIcandidatemodify_support.makBuffalotransaction')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

def makeCowtransaction(*args):
    print('GUIcandidatemodify_support.makeCowtransaction')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

def onClickBorrowCheckbox(*args):
    print('GUIcandidatemodify_support.onClickBorrowCheckbox')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

def onClickBuffaloRadio(*args):
    print('GUIcandidatemodify_support.onClickBuffaloRadio')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

def onClickCowRadio(*args):
    print('GUIcandidatemodify_support.onClickCowRadio')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

def onClickReturnCheckbox(*args):
    print('GUIcandidatemodify_support.onClickReturnCheckbox')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

def saveStatus(*args):
    print('GUIcandidatemodify_support.saveStatus')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

def saveTransaction(*args):
    print('GUIcandidatemodify_support.saveTransaction')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

def searchTransaction(*args):
    print('GUIcandidatemodify_support.searchTransaction')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

def viewTransactionList(*args):
    print('GUIcandidatemodify_support.viewTransactionList')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

if __name__ == '__main__':
    GUIcandidatemodify.start_up()





